"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.INTERNAL_SERVER_ERROR = "Internal Server Error";
exports.REQUEST_PARAMETER_NOT_PROPER = "Bad Request";
exports.DUPLICATE_USER = "Duplicate user";
exports.USER_NOT_FOUND = "User Not Registered";
exports.USER_HAS_BEEN_DEACTIVATED = "User Not Active";
exports.ROLE_NOT_ASSIGNED = "Role not assigned";
exports.ROLE_NOT_FOUND = "Role not found";
exports.DUPLICATE_ROLE = "Duplicate role";
exports.FEATURE_NOT_ASSIGNED = "Feature not assigned";
